server:
  port: 0

spring:
  application:
    name: springboot-app-test
  
  # Redis Configuration for Tests
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 2000ms

# Logging Configuration for Tests
logging:
  level:
    com.example.springbootapp: INFO
    org.springframework.data.redis: WARN
    org.testcontainers: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"